'use strict';
const $=id=>document.getElementById(id),editing=new URLSearchParams(location.search).get('edition')==='1';
const categories={lieu:'Lieux',residence:'Résidences',restaurant:'Bars & restaurants',commerce:'Commerces',culture:'Culture'};
const legacyIcons={lieu:'map-pin',residence:'house',restaurant:'wine',commerce:'storefront',culture:'buildings'};
const iconOptions={"first-aid-kit":"Hôpital","t-shirt":"Friperie","needle":"Tatouage","car":"Garage","bowl-food":"Cuisine indienne","palette":"Galerie","flower-lotus":"Céramique","basket":"Épicerie","camera":"Studio photo","beer-bottle":"Pub — bouteille","users-three":"Centre communautaire","coffee":"Café","film-slate":"Cinéma","barbell":"Sport","disco-ball":"Club","tree":"Parc","joystick":"Arcade","swimming-pool":"Piscine","storefront":"Marché","bowl-steam":"Cuisine asiatique","beer-stein":"Pub — chope","cross":"Cimetière","fork-knife":"Restaurant","rainbow":"Lieu LGBTQ+","drop":"Spa","person-simple-tai-chi":"Yoga","key":"Agence immobilière","chalkboard-teacher":"École","paw-print":"Vétérinaire","books":"Librairie","person-simple":"Danse","flower":"Fleuriste","bank":"Musée","martini":"Cocktails","armchair":"Antiquaire","mask-happy":"Théâtre","crown":"Hôtel","fire-truck":"Pompiers","scales":"Avocats","wine":"Bar","cooking-pot":"Brasserie","shield-star":"Police","gavel":"Tribunal","graduation-cap":"Université","diamond":"Bijouterie","music-notes":"Opéra","house":"Résidence","map-pin":"Autre lieu","buildings":"Bâtiment"};
const zones={east:{label:'East End · £',color:'#bd7868'},south:{label:'South London · ££',color:'#bc9a63'},north:{label:'North London · £££',color:'#929f7b'},west:{label:'West London · ££££',color:'#899fb5'},central:{label:'Central London · £££££',color:'#b7a0ba'}};
function placeColor(p){return zones[p.zone]?.color||'#c4a66b'}
function placeLabel(p){return [p.type,zones[p.zone]?.label].filter(Boolean).join(' · ')}
function inferZone(p){return p.lng<-.19?'west':p.lat<51.49?'south':p.lng>-.085?'east':p.lat>51.535?'north':'central'}
function fitPlaces(duration=0){if(!map||!places.length)return;const bounds=new maplibregl.LngLatBounds();places.forEach(p=>bounds.extend([p.lng,p.lat]));const desktop=innerWidth>850;map.fitBounds(bounds,{padding:{top:130,bottom:80,left:desktop&&!$('directory').hidden?390:60,right:desktop&&editing&&!$('editor').hidden?390:60},maxZoom:14,duration})}
const dataSource=document.querySelector('meta[name="rose-map-data"]')?.content;
const dataURL=dataSource?new URL(dataSource,location.href).href:'';
function readPlaces(text){
  if(text.trimStart().startsWith('{'))return JSON.parse(text);
  const block=new DOMParser().parseFromString(text,'text/html').querySelector('script#map-data[type="application/json"]');
  if(!block)throw Error('La page des lieux doit contenir le bloc map-data.');
  return JSON.parse(block.textContent);
}
function exportPage(){return '<!doctype html>\n<html lang="fr"><head><meta charset="utf-8"><title>Lieux de Londres</title></head><body>\n<script type="application/json" id="map-data">\n'+JSON.stringify({version:2,places},null,2).replace(/</g,'\\u003c')+'\n</script>\n</body></html>'}
const KEY='roses-london-draft-v1',CACHE='roses-geocode-v1';
let places=[],publishedPlaces=[],markers=[],map,draftMarker,active='all',selectedId,lastRequest=0,searchBusy=false;
const motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;
function message(text){$('status').textContent=text}
function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n}
function safeURL(value){if(!value)return '';try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
function validate(data){if(!data||!Array.isArray(data.places)||data.places.length>500)throw Error('Fichier invalide : 500 lieux maximum.');const ids=new Set();return data.places.map(p=>{if(!p||!p.id||ids.has(String(p.id))||typeof p.name!=='string'||!p.name.trim()||!Object.hasOwn(categories,p.category||'lieu')||(p.zone&&!Object.hasOwn(zones,p.zone))||(p.icon&&!Object.hasOwn(iconOptions,p.icon))||!Number.isFinite(p.lng)||!Number.isFinite(p.lat)||p.lng<-.55||p.lng>.35||p.lat<51.25||p.lat>51.75)throw Error('Un lieu est invalide ou situé hors de Londres.');ids.add(String(p.id));return {id:String(p.id),name:p.name.slice(0,100),category:p.category||'lieu',zone:p.zone||inferZone(p),type:String(p.type||categories[p.category||'lieu']).slice(0,80),icon:p.icon||legacyIcons[p.category||'lieu'],address:String(p.address||'').slice(0,250),description:String(p.description||'').slice(0,1500),lng:p.lng,lat:p.lat,image:safeURL(p.image),link:safeURL(p.link),example:!!p.example,positionPrecision:['building','street','postcode'].includes(p.positionPrecision)?p.positionPrecision:'building'}})}
function persist(){try{localStorage.setItem(KEY,JSON.stringify({version:2,places}));message('Brouillon enregistré sur cet appareil. Exportez pour publier.')}catch{message('Stockage local indisponible : exportez pour conserver vos lieux.')}}
function filtered(){const q=$('search').value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return places.filter(p=>(active==='all'||p.zone===active)&&(p.name+' '+p.address+' '+p.description+' '+placeLabel(p)).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(q))}
function renderPins(){
  markers.forEach(marker=>marker.remove());markers=[];
  if(!map)return;
  for(const place of filtered()){
    const pin=el('button',undefined,'pin');pin.type='button';
    pin.title=place.name;pin.setAttribute('aria-label',pin.title);
    pin.style.setProperty('--place-color',placeColor(place));
    pin.append(el('i',undefined,'ph-thin ph-'+place.icon));
    pin.addEventListener('click',event=>{
      event.stopPropagation();
      showPlace(place);
    });
    markers.push(new maplibregl.Marker({element:pin}).setLngLat([place.lng,place.lat]).addTo(map));
  }
}
function render(){
  const rows=filtered();$('count').textContent=rows.length+' adresse'+(rows.length===1?'':'s');$('places').replaceChildren();
  if(!rows.length)$('places').append(el('p','Aucune adresse pour cette recherche.','empty'));
  rows.forEach(p=>{const row=el('button',undefined,'place-row');row.type='button';row.style.setProperty('--place-color',placeColor(p));const icon=el('span',undefined,'place-symbol');icon.append(el('i',undefined,'ph-thin ph-'+p.icon));row.append(icon);const content=el('div');content.append(el('strong',p.name),el('small',placeLabel(p)+(p.example?' · exemple':'')));row.append(content);row.addEventListener('click',()=>showPlace(p));$('places').append(row)});
  renderPins();
}
function showPlace(p){selectedId=p.id;const box=$('detail-content');$('detail').style.setProperty('--place-color',placeColor(p));box.replaceChildren();if(p.image){const img=el('img');img.src=p.image;img.alt='';img.addEventListener('error',()=>img.remove());box.append(img)}const copy=el('div',undefined,'detail-copy');const symbol=el('span',undefined,'detail-symbol');symbol.append(el('i',undefined,'ph-thin ph-'+p.icon));copy.append(symbol,el('small',placeLabel(p)+(p.example?' · exemple':'')),el('h2',p.name),el('p',p.address),el('p',p.description));if(p.link){const a=el('a','Ouvrir sur le forum ↗');a.href=p.link;a.target='_blank';a.rel='noopener';copy.append(a)}if(editing){const edit=el('button','Modifier');edit.onclick=()=>editPlace(p);const remove=el('button','Supprimer');remove.onclick=()=>{if(!confirm('Supprimer « '+p.name+' » du brouillon ?'))return;places=places.filter(x=>x.id!==p.id);persist();render();$('detail').hidden=true};copy.append(edit,remove)}box.append(copy);$('detail').hidden=false;map?.easeTo({center:[p.lng,p.lat],zoom:16,padding:{left:innerWidth>850?350:0,right:editing&&innerWidth>850?350:0},duration:motion?700:0});if(innerWidth<850)$('directory').hidden=true;if(editing)$('editor').hidden=true}
function point(lng,lat){$('lng').value=lng.toFixed(6);$('lat').value=lat.toFixed(6);if(!map)return;if(!draftMarker){draftMarker=new maplibregl.Marker({color:'#c4a66b',draggable:true}).setLngLat([lng,lat]).addTo(map);draftMarker.on('dragend',()=>{const c=draftMarker.getLngLat();point(c.lng,c.lat)})}else draftMarker.setLngLat([lng,lat])}
function editPlace(p){$('detail').hidden=true;$('editor').hidden=false;for(const key of ['name','zone','type','icon','description','image','link','address','lng','lat'])$(key).value=p[key]||'';$('place-id').value=p.id;$('place-form').dataset.category=p.category;point(p.lng,p.lat)}
function resetForm(){$('place-form').reset();delete $('place-form').dataset.category;$('place-id').value='';$('address').value='';$('results').replaceChildren();draftMarker?.remove();draftMarker=null;$('detail').hidden=true;$('editor').hidden=false}
async function geocode(event){event.preventDefault();if(searchBusy)return;const query=$('address').value.trim();if(!query)return;searchBusy=true;$('find-address').disabled=true;try{let cache={};try{cache=JSON.parse(localStorage.getItem(CACHE)||'{}')}catch{};let results=cache[query.toLowerCase()];if(!results){if(Date.now()-lastRequest<1200)throw Error('Patientez un instant avant une nouvelle recherche.');lastRequest=Date.now();const url=new URL('https://nominatim.openstreetmap.org/search');url.search=new URLSearchParams({q:query,format:'jsonv2',limit:'5',countrycodes:'gb',viewbox:'-0.55,51.75,0.35,51.25',bounded:'1','accept-language':'fr'});message('Recherche de l’adresse…');const response=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('La recherche est temporairement indisponible. Placez le repère directement sur la carte.');results=await response.json();cache[query.toLowerCase()]=results;try{localStorage.setItem(CACHE,JSON.stringify(cache))}catch{}}$('results').replaceChildren();results.forEach(result=>{const b=el('button',result.display_name);b.type='button';b.onclick=()=>{point(Number(result.lon),Number(result.lat));map?.easeTo({center:[Number(result.lon),Number(result.lat)],zoom:16,duration:motion?700:0});message('Position trouvée. Vous pouvez déplacer le repère doré.')};$('results').append(b)});message(results.length?'Choisissez une adresse dans les résultats.':'Aucune adresse trouvée : essayez le nom de la rue ou cliquez sur la carte.')}catch(error){message(error.message)}finally{searchBusy=false;$('find-address').disabled=false}}
async function start(){document.body.classList.toggle('editing',editing);$('editor').hidden=!editing;$('editor-link').hidden=editing;$('toggle-editor').hidden=false;
try{if(!dataURL||dataSource.includes('URL_PAGE_LIEUX'))throw Error('Renseignez l’URL de la page des lieux dans rose-map-data.');const response=await fetch(dataURL,{cache:'no-store'});if(!response.ok)throw Error('Impossible de charger les lieux.');places=validate(readPlaces(await response.text()));publishedPlaces=places.map(p=>({...p}));if(editing){try{const draft=localStorage.getItem(KEY);if(draft){const data=JSON.parse(draft);if(data.version>=2)places=validate(data);else{
const merged=new Map(publishedPlaces.map(p=>[p.id,p]));validate(data).filter(p=>!(p.example&&/^ex[1-6]$/.test(p.id))).forEach(p=>{const current=merged.get(p.id);merged.set(p.id,current?{...p,zone:current.zone,type:current.type,icon:current.icon}:p)});places=[...merged.values()];
}}}catch{message('Le brouillon local est illisible. Les lieux publiés sont affichés.')}}}catch(error){message(error.message)}
for(const [key,label] of Object.entries({all:'Tout',...Object.fromEntries(Object.entries(zones).map(([key,zone])=>[key,zone.label]))})){const b=el('button',label);b.type='button';if(zones[key])b.style.setProperty('--place-color',zones[key].color);b.classList.toggle('zone-filter',key!=='all');b.setAttribute('aria-pressed',String(key==='all'));b.onclick=()=>{active=key;Array.from($('filters').children).forEach(n=>n.setAttribute('aria-pressed',String(n===b)));render()};$('filters').append(b)}render();
if(!window.maplibregl){message('Le moteur de carte n’a pas chargé. Vérifiez votre connexion puis rechargez la page.');return}
try{const response=await fetch('https://tiles.openfreemap.org/styles/dark',{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Fond de carte indisponible.');const style=await response.json();style.layers=style.layers.filter(layer=>layer.type!=='symbol'||['transportation_name','water_name'].includes(layer['source-layer']));for(const layer of style.layers){if(layer.type==='background')layer.paint['background-color']='#191919';if(layer.type==='fill')layer.paint['fill-color']=layer['source-layer']==='water'?'#101010':layer['source-layer']==='building'?'#3b3b3b':'#222222';if(layer.type==='line'&&layer.paint?.['line-color'])layer.paint['line-color']=layer['source-layer']==='waterway'?'#111111':'#505050';if(layer.type==='symbol'){layer.paint={...layer.paint,'text-color':'#c4c4c4','text-halo-color':'#202020'}}}
// Draw all ground layers before buildings, then keep street labels above them.
style.layers=[...style.layers.filter(layer=>layer.type!=='symbol'),...style.layers.filter(layer=>layer.type==='symbol')];
const buildings=style.layers.find(l=>l['source-layer']==='building');if(buildings){delete buildings.paint['fill-outline-color'];buildings.paint['fill-antialias']=false;style.layers.splice(style.layers.findIndex(l=>l.type==='symbol'),0,{id:'roses-buildings',type:'fill-extrusion',source:buildings.source,'source-layer':'building',minzoom:14,filter:['!=',['get','hide_3d'],true],paint:{'fill-extrusion-color':'#626262','fill-extrusion-height':['coalesce',['get','render_height'],8],'fill-extrusion-base':['coalesce',['get','render_min_height'],0],'fill-extrusion-opacity':1}})}
map=new maplibregl.Map({container:'map',style,center:[-.145,51.509],zoom:14.8,pitch:52,bearing:-22,maxPitch:65,maxBounds:[[-.55,51.25],[.35,51.75]],attributionControl:false});map.addControl(new maplibregl.AttributionControl({compact:false}),'bottom-right');map.addControl(new maplibregl.NavigationControl({showCompass:true}),'bottom-left');map.on('load',()=>{fitPlaces();render();message('')});map.on('moveend',renderPins);map.on('resize',renderPins);map.on('error',()=>message('Certaines données cartographiques sont indisponibles. Vérifiez votre connexion.'));if(editing)map.on('click',event=>{if(event.originalEvent.target.closest('button'))return;point(event.lngLat.lng,event.lngLat.lat);$('editor').hidden=false;message('Position ajustée. Complétez puis enregistrez le lieu.')});}catch(error){message('Carte indisponible : '+error.message)}}
$('toggle-editor').onclick=()=>{if(!editing){const url=new URL(location.href);url.searchParams.set('edition','1');location.href=url.href;return} $('editor').hidden=!$('editor').hidden};
$('search').oninput=render;$('toggle-directory').onclick=()=>{$('directory').hidden=!$('directory').hidden};$('close-detail').onclick=()=>{$('detail').hidden=true;if(editing)$('editor').hidden=false};$('perspective').onclick=()=>{if(!map)return;const three=map.getPitch()<10;map.easeTo({pitch:three?52:0,bearing:three?-22:0,duration:motion?500:0});$('perspective').setAttribute('aria-pressed',String(three))};$('recenter').onclick=()=>fitPlaces(motion?650:0);
$('address-search').onsubmit=geocode;$('new-place').onclick=resetForm;
$('place-form').onsubmit=event=>{event.preventDefault();if(!editing)return;const data={id:$('place-id').value||crypto.randomUUID(),name:$('name').value.trim(),category:$('place-form').dataset.category||($('icon').value==='house'?'residence':'lieu'),zone:$('zone').value,type:$('type').value.trim(),icon:$('icon').value,address:$('address').value,description:$('description').value,image:$('image').value,link:$('link').value,positionPrecision:places.find(p=>p.id===$('place-id').value)?.positionPrecision||'building',lng:Number($('lng').value),lat:Number($('lat').value)};try{const p=validate({places:[data]})[0];const index=places.findIndex(x=>x.id===p.id);if(index<0)places.push(p);else places[index]=p;persist();render();resetForm()}catch(error){message(error.message)}};
$('export').onclick=()=>{const blob=new Blob([exportPage()],{type:'text/html;charset=utf-8'});const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='lieux.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('Fichier exporté : collez son contenu dans la page HTML des lieux pour publier.')};
$('import').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>2e6)throw Error('Fichier trop volumineux.');const next=validate(readPlaces(await file.text()));if(!confirm('Remplacer le brouillon par les '+next.length+' lieux du fichier ?'))return;places=next;persist();render();resetForm()}catch(error){message(error.message)}finally{event.target.value=''}};
document.getElementById("close-editor").onclick=()=>{document.getElementById("editor").hidden=true};
for(const [key,zone] of Object.entries(zones)){const option=el('option',zone.label);option.value=key;$('zone').append(option)}
for(const [key,label] of Object.entries(iconOptions)){const option=el('option',label);option.value=key;$('icon').append(option)}
$('icon').value='map-pin';
$('load-published').onclick=()=>{if(!publishedPlaces.length)return;if(!confirm('Remplacer ce brouillon par les '+publishedPlaces.length+' adresses publiées ?'))return;places=publishedPlaces.map(p=>({...p}));persist();render();resetForm();fitPlaces(motion?650:0)};
start();
